After: 
  -
---
Name: ecommerce_stockists
Before: 
  - 'mysite/*
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
---

GoogleMapLocationsDOD:
  page_classes_with_map:
    - StockistPage
    - StockistCountryPage
    - StockistSearchPage


