---
Name: ecommerce_stockists
After:
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
Before: 
  - 'mysite/*'
---

GoogleMapLocationsDOD:
  page_classes_with_map:
    - StockistPage
    - StockistCountryPage
    - StockistSearchPage


