---Name: ecommerce_stockistsBefore: 'mysite/*'After: 
  - 
  -   -   - 'framework/*'  - 'cms/*'  -  'ecommerce/*'---GoogleMapLocationsDOD:  page_classes_with_map:    - StockistPage    - StockistCountryPage    - StockistSearchPage